### ISSUE TITLE
May I get a copy of the Synthetic dataset for training the feature extractor?

### ISSUE THREAD

**Issue by ilovecv** [ISICV/ManTraNet#10]
Hi,

Could you please share the synthetic dataset too? I could not find the Dresden Image Database, which is used to generate the synthetic images. Thank you very much!

**Comment by ycf1997** [comment]
Hi, 
Do you obtain the Dresden Image Database?  If yes, could you please share with me? Thank you very much.

**Comment by solenson** [comment]
Hi,
Do you obtain the Dresden Image Database? If yes, could you please share with me? Thank you very much.

**Comment by XiangGD** [comment]
Hi,
Do you obtain the Dresden Image Database? If yes, could you please share with me? Thank you very much.

**Comment by rex-yue-wu** [comment]
Not sure what's going on, I can't access the dataset either. However, I don't think it is a must-have dataset to reproduce the ManTraNet results. All you need is an image dataset with only pristine images. If you want, you can use those images from other sources, e.g., the original images in this [dataset](http://people.ee.ethz.ch/~ihnatova/pynet-bokeh.html). Otherwise, you can use your own photos.
