### ISSUE TITLE
The question about the result in NIST 2016

### ISSUE THREAD

**Issue by ZhuangPeiyu** [ISICV/ManTraNet#9]
Hello! When I test your model in NIST 2016 (total of 564 tampered images), I found some problems.
Which device did you use and how did you test in this dataset? 
In my experiments, I used Nvidia P100 with 16GB memory. But even though I can't test more than 400 tampered images because of the out of memory error.  You said you used the whole dataset in your paper, did you have any strategy in testing?
I am looking forward your answer.

**Comment by CauchyComplete** [comment]
I'm curious too. I've tried with TITAN RTX (24GB), and got out of memory error also.

**Comment by rex-yue-wu** [comment]
This is a good question. I was not aware of the memory issue when I submitted the paper, since I didn't run all evaluations by myself, but asked several junior labmates for help. I tried to contact them to get more details -- they mentioned that they tried different solutions but can't fully recall what were exactly done to get the paper results.  

In addition, I've received several email inquires about the same issue, and luckily some have already reproduce the numbers, and I share his experience below. 

![nist](https://user-images.githubusercontent.com/11779725/118382361-5e3ba600-b5a9-11eb-922f-a80fb5c5eacf.png)
